import {
  BatteryCharging,
  Bike,
  BriefcaseBusiness,
  BrickWall,
  Bug,
  Building,
  Building2,
  Cable,
  Camera,
  Car,
  Circle,
  CircleDot,
  ClipboardCheck,
  Drill,
  Droplet,
  Fence,
  FileCheck,
  FileText,
  Gauge,
  Hammer,
  HardHat,
  House,
  KeyRound,
  Leaf,
  Move3D,
  PackageOpen,
  PaintRoller,
  Paintbrush,
  PanelTop,
  Ruler,
  Scale,
  Settings,
  Shield,
  Snowflake,
  Sofa,
  Sparkles,
  Sprout,
  Square,
  Sun,
  Truck,
  Warehouse,
  Waves,
  Wrench,
  Zap,
  type LucideIcon
} from "lucide-react";
import { iconForService } from "@/lib/service-catalog";

const serviceIconMap: Record<string, LucideIcon> = {
  "battery-charging": BatteryCharging,
  bike: Bike,
  "briefcase-business": BriefcaseBusiness,
  "brick-wall": BrickWall,
  bug: Bug,
  building: Building,
  "building-2": Building2,
  cable: Cable,
  camera: Camera,
  car: Car,
  circle: Circle,
  "circle-dot": CircleDot,
  "clipboard-check": ClipboardCheck,
  drill: Drill,
  droplet: Droplet,
  fence: Fence,
  "file-check": FileCheck,
  "file-text": FileText,
  gauge: Gauge,
  hammer: Hammer,
  "hard-hat": HardHat,
  house: House,
  home: House,
  "key-round": KeyRound,
  leaf: Leaf,
  "move-3d": Move3D,
  "package-open": PackageOpen,
  "paint-roller": PaintRoller,
  paintbrush: Paintbrush,
  "panel-top": PanelTop,
  ruler: Ruler,
  scale: Scale,
  settings: Settings,
  shield: Shield,
  snowflake: Snowflake,
  sofa: Sofa,
  sparkles: Sparkles,
  sprout: Sprout,
  square: Square,
  sun: Sun,
  truck: Truck,
  warehouse: Warehouse,
  waves: Waves,
  wrench: Wrench,
  zap: Zap
};

export function ServiceCategoryIcon({ value, size = 14, className, strokeWidth }: { value: string; size?: number; className?: string; strokeWidth?: number }) {
  const Icon = serviceIconMap[iconForService(value)] ?? BriefcaseBusiness;
  return <Icon size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true" />;
}

export function serviceCategoryIconComponent(value: string) {
  return serviceIconMap[iconForService(value)] ?? BriefcaseBusiness;
}
